"""Golden-vector certification against the Lean spec layer (plan P5).

src/cross_phase/meta_calculus/golden_vectors.json is generated by
`lake exe gccvectors` in gcc-lean-lab (Float shadows of machine-checked
theorems; see its provenance field) and vendored here - this repo never
needs a Lean toolchain. Tolerance rtol 1e-4 (generator prints 6 decimals);
never exact equality.

Updating: regenerate in gcc-lean-lab, copy here AND to
meta-calculus-toolkit/tests/data/, update EXPECTED_SHA256 in both.
"""

import hashlib
import json
from pathlib import Path

import pytest
import torch

from src.cross_phase.meta_calculus.bigeometric import (
    BigeometricConfig,
    BigeometricTransform,
)
from src.cross_phase.meta_calculus.k_formula import KFormulaConfig, compute_k

VECTOR_FILE = (
    Path(__file__).resolve().parents[2]
    / "src" / "cross_phase" / "meta_calculus" / "golden_vectors.json"
)
EXPECTED_SHA256 = "4112e2a2dbf246984dbc8bb3e373c5b5aa9f591e0f007301f8a20ec2c2b608ea"

_VECTORS = json.loads(VECTOR_FILE.read_text())


def test_vector_file_integrity():
    """Vendored vectors must be byte-identical to the Lean-generated file.

    Fails if: hand-edited instead of regenerated.
    """
    digest = hashlib.sha256(VECTOR_FILE.read_bytes()).hexdigest()
    assert digest == EXPECTED_SHA256
    assert "floats are not the proofs" in _VECTORS["provenance"]


def test_bigeometric_transform_matches_bgTransform():
    """g * |g|^(2k-1) must match the Lean bgTransform values exactly in
    shape (sign + magnitude law), within float-print tolerance.

    Clamp OFF: the vectors cover in-window AND boundary k values; the
    guardrail is tested separately (test_meta_calculus_guards) - here we
    pin the raw formula the theorems abs_bgTransform / sign-preservation
    describe.

    Fails if: the exponent wiring (2k-1), the abs, or the sign handling
    drifts from the proved formula.
    """
    t = BigeometricTransform(BigeometricConfig(clamp_k=False, eps=1e-12))
    for case in _VECTORS["bg_transform"]:
        g = torch.tensor([case["g"]], dtype=torch.float64)
        out = t.transform(g, k=case["k"])[0].item()
        assert out == pytest.approx(case["expected"], rel=1e-4, abs=1e-6), case


def test_compute_k_matches_kOf_table():
    """compute_k must agree with the Lean kOf affine table (production
    constants; structure pinned by kOf_strictAntiOn / kOf_mem_Icc).

    The vectors' L range [1, 1e6] keeps k inside the [K_MIN, K_MAX] clamp,
    so clamping cannot mask drift here.

    Fails if: slope/intercept/log-base drift between this snapshot and the
    Lean-pinned affine form (the fork-collapse failure mode).
    """
    config = KFormulaConfig()
    for case in _VECTORS["k_of_L"]:
        got = float(compute_k(case["L"], config))
        assert got == pytest.approx(case["expected_k"], rel=1e-4, abs=1e-6), case
